# docker-compose.yml

version: '3.8' # It's good practice to specify a version

services:
  # Your existing Typesense service (unchanged)
  typesense:
    image: typesense/typesense:27.1
    restart: unless-stopped
    ports:
      - "6211:8108" # Host port 6211 maps to container port 8108
    volumes:
      - ./typesense-data:/data
    command: '--data-dir /data --api-key=avision --enable-cors'

  # --- New Redis Service Added Below ---
  redis:
    image: redis:7-alpine  # Using a specific version is good practice. Alpine is a small, secure image.
    restart: unless-stopped
    ports:
      - "6379:6379" # Host port 6379 maps to the default Redis port 6379 in the container
    volumes:
      - redis_data:/data # Use a named volume to persist Redis data

# Top-level key to define the named volume used by the Redis service
volumes:
  redis_data: