services:
  typesense:
    image: typesense/typesense:27.1
    restart: unless-stopped
    ports:
      - "6211:8108"
    volumes:
      - ./typesense-data:/data
    command: '--data-dir /data --api-key=avision --enable-cors'

